---
drivers:
  daemon:
    drivers:
      kubernetes:
        name: kubernetes
        type: builtin
        handlerData:
          shortName: kubernetes
    features:
      operator:
        - name: "driver:kubernetes"
