---
systems:
  kubernetes:
    description: |
      This system enables Honeydipper to interact with kubernetes clusters. This system
      is intended to be extended to create systems represent actual kubernetes clusters,
      instead of being used directly.

    meta:
      configurations:
        - name: source
          description: >
            The parameters used for fetching kubeconfig for accessing the cluster, should at least contain
            a :code:`type` field. Supported values are :code:`local`, :code:`gcloud-gke`, or :code:`static`.
            For :code:`gcloud-gke` type,
            this should also include :code:`service_account`, :code:`project`, :code:`zone`, and :code:`cluster`.
            For :code:`static` type, this should include :code:`name` that points to
            :code:`drivers.kubernetes.sources.<name>` in the daemon driver config.
        - name: namespace
          description: >
            The namespace of the resources when operating on the resources within the cluster,
            e.g. deployments. By default, :code:`default` namespace is used.

      notes:
        - For example
        - example: |
            ---
            systems:
              my_gke_cluster:
                extends:
                  - kubernetes
                data:
                  source:
                    type: gcloud-gke
                    service_account: ENC[gcloud-kms,...masked...]
                    zone: us-central1-a
                    project: foo
                    cluster: bar
                  namespace: mynamespace

    data:
      kubernetes:
        namespace: default

    functions:
      exec:
        driver: kubernetes
        rawAction: exec
        parameters:
          source: $sysData.source
          namespace: $?sysData.namespace
          pod: $ctx.pod
          container: $ctx.container
          shell: $?ctx.shell
          script: $?ctx.script
          command: $?ctx.command
        export:
          output: '{{ .data.output }}'
          exit_code: '{{ .data.exit_code }}'

        description: >
          This function executes a command in a container in the kubernetes cluster. It is a wrapper for the kubernetes driver exec rawAction.
          It leverages the pre-configured system data to access the kubernetes cluster.

        meta:
          inputs:
            - name: pod
              description: The pod name to execute the command in

            - name: container
              description: The container name to execute the command in

            - name: shell
              description: The shell to use for executing the command, e.g. :code:`/bin/sh` or :code:`/bin/bash`

            - name: script
              description: The actual command/script to execute in the specified shell

          notes:
            - See below for example
            - example: |
                ---
                workflow:
                  run_script_in_k8s:
                    steps:
                      - call_function: my-k8s-cluster.exec
                        with:
                          pod: mypod
                          container: mycontainer
                          shell: /bin/bash
                          script: |
                            echo "Hello from Kubernetes!" > /tmp/hello.txt
      waitForJobPods:
        driver: kubernetes
        rawAction: waitForJobPods
        parameters:
          source: $sysData.source
          namespace: $?sysData.namespace
          job: $ctx.jobid
        export:
          pod_names: $?data.pod_names
          pod_ips: $?data.pod_ips

        description: >
          This function is a wrapper to the kubernetes driver waitForJobPods rawAction.
          It leverages the pre-configured system data to access the kubernetes cluster.

        meta:
          inputs:
            - name: jobid
              description: The job ID to wait for its pods to be ready

          notes:
            - See below for example
            - example: |
                ---
                workflow:
                  run_simple_job:
                    steps:
                      - call_function: my-k8s-cluster.createJob
                        with:
                          job: $ctx.job
                      - call_function: my-k8s-cluster.waitForJobPods
                        with:
                          jobid: $ctx.jobid
      recycleDeployment:
        driver: kubernetes
        rawAction: recycleDeployment
        parameters:
          source: $sysData.source
          namespace: $?sysData.namespace
          deployment: $ctx.deployment

        description: >
          This function is a wrapper to the kubernetes driver recycleDeployment rawAction.
          It leverages the pre-configured system data to access the kubernetes cluster.

        meta:
          inputs:
            - name: deployment
              description: The selector for identify the deployment to restart, e.g. :code:`app=nginx`

          notes:
            - See below for example
            - example: |
                ---
                rules:
                  - when:
                      source:
                        system: opsgenie
                        trigger: alert
                    do:
                      steps:
                        - if_match:
                            alert_message: :regex:foo-deployment
                          call_function: my-k8s-cluster.recycleDeployment
                          with:
                            deployment: app=foo
                        - if_match:
                            alert_message: :regex:bar-deployment
                          call_function: my-k8s-cluster.recycleDeployment
                          with:
                            deployment: app=bar

      deleteJob:
        driver: kubernetes
        rawAction: deleteJob
        parameters:
          source: $sysData.source
          namespace: $?sysData.namespace
          job: $ctx.jobid
        export:
          links:
            k8s_job:
              text: 'deleted'

        description: >
          This function deletes a kubernetes job specified by the job name in :code:`.ctx.jobid`.
          It leverages the pre-configured system data to access the kubernetes cluster.

        meta:
          inputs:
            - name: jobid
              description: The name of the kubernetes job

          notes:
            - See below for example
            - example: |
                ---
                workflows:
                  run_myjob:
                    - call_function: myk8scluster.createJob
                      ...
                      # this function exports .ctx.jobid
                    - call_function: myk8scluster.waitForJob
                      ...
                    - call_function: myk8scluster.deleteJob
            - >
              This function is not usually used directly by users. It is added to the :ref:`run_kubernetes` workflow so
              that, upon successful completion, the job will be deleted. In rare cases, you can use the wrapper workflow
              :ref:`cleanup_k8s_job` to delete a job.

      createJob:
        driver: kubernetes
        rawAction: createJob
        parameters:
          source: $sysData.source
          namespace: $?sysData.namespace
          job: $ctx.job
          fromCronJob: $?ctx.fromCronJob
          start_immediately: '{{ default true .ctx.start_immediately }}'
        export:
          jobid: $data.metadata.name
          links: $?sysData.types.{{ .sysData.source.type }}.joblinks

        description: >
          This function creates a k8s run-to-completion job with given job spec data structure. It is a wrapper
          for the kubernetes driver createJob rawAction.  It leverages the pre-configured system data to access
          the kubernetes cluster. It is recommmended to use the helper workflows instead of using the job handling
          functions directly.

        meta:
          inputs:
            - name: job
              description: The job data structure following the specification for a run-to-completion job manifest yaml file.

            - name: fromCronJob
              description: >
                Creating the job based on the definition of a cronjob, in the form of :code:`namespace/cronjob`. If the namespace
                is omitted, the current namespace where the job is being created will be used for looking up the cronjob.

            - name: start_immediately
              description: >
                Optional, defaults to :code:`true`. When set to :code:`false`, the job is created in suspended state and must be
                started later by calling :code:`startJob`.

          exports:
            - name: jobid
              description: The job ID of the created job

          notes:
            - See below for example
            - example: |
                ---
                workflow:
                  create_job:
                    call_function: my-k8s-cluster.createJob
                    with:
                      job:
                        apiVersion: batch/v1
                        kind: Job
                        metadata:
                          name: pi
                        spec:
                          template:
                            spec:
                              containers:
                              - name: pi
                                image: perl
                                command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
                              restartPolicy: Never
                          backoffLimit: 4

      startJob:
        driver: kubernetes
        rawAction: startJob
        parameters:
          source: $sysData.source
          namespace: $?sysData.namespace
          job: $ctx.jobid

        description: >
          This function starts a previously suspended kubernetes job. It is intended to be paired with :code:`createJob`
          when the job was created with :code:`start_immediately=false`.

        meta:
          inputs:
            - name: jobid
              description: The job ID of the suspended kubernetes job to start.

          notes:
            - See below for example
            - example: |
                ---
                workflow:
                  create_then_start_job:
                    steps:
                      - call_function: my-k8s-cluster.createJob
                        with:
                          start_immediately: false
                          job: $ctx.job
                      - call_function: my-k8s-cluster.startJob
                        with:
                          jobid: $ctx.jobid
                      - call_function: my-k8s-cluster.waitForJob
                        with:
                          job: $ctx.jobid

      waitForJob:
        driver: kubernetes
        rawAction: waitForJob
        parameters:
          source: $sysData.source
          namespace: $?sysData.namespace
          job: $ctx.jobid
        export:
          job_status: '{{ and (eq .labels.status "success") (eq (int .data.status.failed) 0) | ternary "success" "failure" }}'

        description: >
          This function blocks and waiting for a k8s run-to-completion job to finish. It is a wrapper
          for the kubernetes driver waitForJob rawAction.  It leverages the pre-configured system data to access
          the kubernetes cluster. It is recommmended to use the helper workflows instead of using the job handling
          functions directly.

        meta:
          inputs:
            - name: job
              description: The job id that the function will wait for to reach terminated states

          exports:
            - name: job_status
              description: The status of the job, either :code:`success` or :code:`failure`

          notes:
            - See below for example
            - example: |
                ---
                workflow:
                  run_simple_job:
                    steps:
                      - call_function: my-k8s-cluster.createJob
                        with:
                          job: $ctx.job
                      - call_function: my-k8s-cluster.waitForJob
                        with:
                          job: $ctx.jobid
                      - call_workflow: notify
                        with:
                          message: the job status is {{ .job_status }}

      getJobLog:
        driver: kubernetes
        rawAction: getJobLog
        parameters:
          source: $sysData.source
          namespace: $?sysData.namespace
          job: $ctx.jobid
        export:
          log: $?data.log
          output: $?data.output

        description: >
          This function fetch all the logs for a k8s job with the given jobid. It is a wrapper
          for the kubernetes driver getJobLog rawAction.  It leverages the pre-configured system data to access
          the kubernetes cluster. It is recommmended to use the helper workflows instead of using the job handling
          functions directly.

        meta:
          inputs:
            - name: job
              description: The ID of the job to fetch logs for

          exports:
            - name: log
              description: The logs organized in a map of pod name to a map of container name to logs.
            - name: output
              description: The logs all concatinated into a single string

          notes:
            - See below for example
            - example: |
                ---
                workflow:
                  run_simple_job:
                    steps:
                      - call_function: my-k8s-cluster.createJob
                        with:
                          job: $ctx.job
                      - call_function: my-k8s-cluster.waitForJob
                        with:
                          job: $ctx.jobid
                      - call_workflow: my-k8s-cluster.getJobLog
                        with:
                          job: $ctx.jobid

      createPVC:
        driver: kubernetes
        rawAction: createPVC
        parameters:
          source: $sysData.source
          namespace: $?sysData.namespace
          pvc: $ctx.pvc
          ignore_already_exists: '{{ empty .ctx.ignore_already_exists | not | return }}'
        export:
          pvc_name: $?data.metadata.name
          pvc_status: $?data.status

        description: >
          This function creates a Persistent Volume Claim.

        meta:
          inputs:
            - name: pvc
              description: The PersistentVolumeClaim specification.

          exports:
            - name: pvc_name
              description: The name of the pvc
            - name: pvc_status
              description: The status of the pvc

          notes:
            - See below for example
            - example: |
                ---
                workflow:
                  generate_pvc:
                    steps:
                      - call_function: my-k8s-cluster.createPVC
                        with:
                          pvc:
                            apiVersion: v1
                            kind: PersistentVolumeClaim
                            metadata:
                              name: pvc-demo
                            spec:
                              accessModes:
                                - ReadWriteOnce
                              resources:
                                requests:
                                  storage: 30Gi
                              storageClassName: standard-rwo

      deletePVC:
        driver: kubernetes
        rawAction: deletePVC
        parameters:
          source: $sysData.source
          namespace: $?sysData.namespace
          pvc: $ctx.pvc_name

        description: >
          This function deletes a Persistent Volume Claim.

        meta:
          inputs:
            - name: pvc_name
              description: The name of the PersistentVolumeClaim.

          notes:
            - See below for example
            - example: |
                ---
                workflow:
                  cleanup_pvc:
                    steps:
                      - call_function: my-k8s-cluster.deletePVC
                        with:
                          pvc_name: pvc-demo
